run original architecture - partial train data

In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys
sys.path.append('/'.join(sys.path[0].split('/')[:-1]))

from modules.full_pipeline_evaluation import main

## Output after first pass with original architecture and data standardized based on monthly statistics

In [3]:
training_ds, batch1, batch2, output1, output2 = main()

Reading confing file and set up folders...
Load data files...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Loading data to RAM...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Time: 34.14s


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Loading data to RAM...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Time: 6.12s
Define model...
Train model...
Epoch : 0

In [4]:
batch1

tensor([[[-2.7417, -0.9732, -0.8322,  ...,  0.0612,  1.5666,  1.8796],
         [-2.7273, -1.0314, -0.8073,  ...,  0.1223,  0.5305,  0.5726],
         [-3.0948, -1.3137, -0.8365,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [-0.1172, -0.2636, -0.8247,  ..., -0.1220,  0.9766,  0.8882],
         [-0.1394, -0.6999, -0.8247,  ..., -0.1220,  1.7180,  1.9259],
         [-0.1639, -0.4418, -0.8262,  ..., -0.0609,  1.5136,  1.8794]],

        [[-1.0580,  1.9544,  0.1291,  ...,  0.0612,  1.5666,  1.8796],
         [-1.0473,  1.2064, -0.0188,  ...,  0.1223,  0.5305,  0.5726],
         [-1.0173,  1.9259,  0.2265,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [ 0.9470, -0.9927,  1.6042,  ..., -0.1220,  0.9766,  0.8882],
         [ 1.3995, -0.4889,  1.5115,  ..., -0.1220,  1.7180,  1.9259],
         [ 1.0788, -1.1414,  1.5665,  ..., -0.0609,  1.5136,  1.8794]],

        [[ 0.8247, -1.4578, -0.8323,  ...,  0.0612,  1.5666,  1.8796],
         [ 0.7983, -0.8014, -0.8369,  ...,  0

In [5]:
output1

tensor([[[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        ...,

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]]], device='cuda:0', grad_fn=<AsStridedBackward>)

In [6]:
batch2

tensor([[[    nan,     nan,  1.7530,  ...,  0.0612,  1.5666,  1.8796],
         [    nan,     nan,  1.7612,  ...,  0.1223,  0.5305,  0.5726],
         [    nan,     nan,  1.7276,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [    nan,     nan, -0.8073,  ..., -0.1220,  0.9766,  0.8882],
         [    nan,     nan, -0.8247,  ..., -0.1220,  1.7180,  1.9259],
         [    nan,     nan, -0.8262,  ..., -0.0609,  1.5136,  1.8794]],

        [[    nan,     nan, -0.8225,  ...,  0.0612,  1.5666,  1.8796],
         [    nan,     nan, -0.8169,  ...,  0.1223,  0.5305,  0.5726],
         [    nan,     nan, -0.8169,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [    nan,     nan,  0.0767,  ..., -0.1220,  0.9766,  0.8882],
         [    nan,     nan,  0.3039,  ..., -0.1220,  1.7180,  1.9259],
         [    nan,     nan,  0.1727,  ..., -0.0609,  1.5136,  1.8794]],

        [[    nan,     nan, -0.8323,  ...,  0.0612,  1.5666,  1.8796],
         [    nan,     nan, -0.8369,  ...,  0

## Same but no batch normalization layers or shuffling indices

In [3]:
training_ds, batch1, batch2, output1, output2 = main()

Reading confing file and set up folders...
Load data files...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Loading data to RAM...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Time: 32.98s


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Loading data to RAM...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Time: 6.62s
Define model...
Train model...
Epoch : 0

In [15]:
batch1

tensor([[[-1.4793, -0.7382, -0.8232,  ...,  0.0612,  1.5666,  1.8796],
         [-1.6047, -0.5688, -0.8184,  ...,  0.1223,  0.5305,  0.5726],
         [-1.7322, -0.6811, -0.8183,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [ 0.7499,  0.1848, -0.8445,  ..., -0.1220,  0.9766,  0.8882],
         [ 0.6280,  0.4632, -0.8445,  ..., -0.1220,  1.7180,  1.9259],
         [ 0.7759,  0.8954, -0.8363,  ..., -0.0609,  1.5136,  1.8794]],

        [[-1.4293, -0.4989, -0.8232,  ...,  0.0612,  1.5666,  1.8796],
         [-1.5871, -0.5268, -0.8184,  ...,  0.1223,  0.5305,  0.5726],
         [-1.7143, -0.6677, -0.8183,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [ 1.0356, -0.0156, -0.8445,  ..., -0.1220,  0.9766,  0.8882],
         [ 0.9615,  0.3028, -0.8445,  ..., -0.1220,  1.7180,  1.9259],
         [ 1.0397,  0.5955, -0.8363,  ..., -0.0609,  1.5136,  1.8794]],

        [[-1.2753, -0.3466, -0.8232,  ...,  0.0612,  1.5666,  1.8796],
         [-1.4425, -0.5281, -0.8184,  ...,  0

In [17]:
aux.shape

torch.Size([120, 3072, 14])

In [16]:
aux = batch1.cpu().abs() < 1e-4
aux.sum()

tensor(177)

In [5]:
output1

tensor([[[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        ...,

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]]], device='cuda:0', grad_fn=<AsStridedBackward>)

In [6]:
batch2

tensor([[[    nan,     nan,  0.6854,  ...,  0.0612,  1.5666,  1.8796],
         [    nan,     nan,  0.7731,  ...,  0.1223,  0.5305,  0.5726],
         [    nan,     nan,  0.5640,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [    nan,     nan, -0.8445,  ..., -0.1220,  0.9766,  0.8882],
         [    nan,     nan, -0.8445,  ..., -0.1220,  1.7180,  1.9259],
         [    nan,     nan, -0.8363,  ..., -0.0609,  1.5136,  1.8794]],

        [[    nan,     nan,  1.1732,  ...,  0.0612,  1.5666,  1.8796],
         [    nan,     nan,  1.2458,  ...,  0.1223,  0.5305,  0.5726],
         [    nan,     nan,  1.0839,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [    nan,     nan, -0.8445,  ..., -0.1220,  0.9766,  0.8882],
         [    nan,     nan, -0.8445,  ..., -0.1220,  1.7180,  1.9259],
         [    nan,     nan, -0.8363,  ..., -0.0609,  1.5136,  1.8794]],

        [[    nan,     nan,  1.5222,  ...,  0.0612,  1.5666,  1.8796],
         [    nan,     nan,  1.5716,  ...,  0

## With original data

In [6]:
training_ds, batch1, batch2, output1, output2 = main()

Reading confing file and set up folders...
Load data files...
Loading data to RAM...
Time: 34.51s
Loading data to RAM...
Time: 5.95s
Define model...
Train model...
Epoch : 0

In [7]:
batch1

tensor([[[ 2.0119,  2.5639,  1.7865,  ...,  0.0612,  1.5666,  1.8796],
         [ 2.0480,  2.2445,  1.6485,  ...,  0.1223,  0.5305,  0.5726],
         [ 2.0642,  3.1423,  1.8212,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [ 2.3161,  2.0949,  1.1572,  ..., -0.1220,  0.9766,  0.8882],
         [ 2.2523,  2.0853,  0.9008,  ..., -0.1220,  1.7180,  1.9259],
         [ 2.3050,  2.1543,  1.0027,  ..., -0.0609,  1.5136,  1.8794]],

        [[ 2.4328,  1.8347, -0.8023,  ...,  0.0612,  1.5666,  1.8796],
         [ 2.4625,  2.2491, -0.8023,  ...,  0.1223,  0.5305,  0.5726],
         [ 2.4342,  2.3526, -0.8023,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [ 2.4018,  2.1886,  1.7423,  ..., -0.1220,  0.9766,  0.8882],
         [ 2.4226,  2.3404,  1.8433,  ..., -0.1220,  1.7180,  1.9259],
         [ 2.3862,  2.2094,  1.8541,  ..., -0.0609,  1.5136,  1.8794]],

        [[ 2.6291,  2.1988, -0.8023,  ...,  0.0612,  1.5666,  1.8796],
         [ 2.6028,  2.4238, -0.8023,  ...,  0

In [8]:
aux = batch1.cpu().abs() < 1e-4
aux.sum()

tensor(47)

In [9]:
output1

tensor([[[-0.1132, -0.1517],
         [-1.0113,  0.3003],
         [-0.8521,  0.1761],
         ...,
         [-0.1391,  0.2590],
         [-0.0472,  0.7690],
         [ 0.4145,  0.1268]],

        [[ 0.6500,  0.1034],
         [ 0.1337, -0.1135],
         [ 0.0316,  0.9644],
         ...,
         [-0.2682,  0.6434],
         [-0.4964,  0.4144],
         [ 0.4058,  0.0922]],

        [[ 0.1225,  0.5214],
         [-0.1627, -0.5289],
         [-0.6756,  1.1678],
         ...,
         [ 0.0179,  0.5190],
         [ 0.1062,  1.0352],
         [ 0.5212, -0.0426]],

        ...,

        [[ 0.5973,  0.7328],
         [-0.5028,  1.0879],
         [-0.0239,  0.9253],
         ...,
         [-0.4649, -0.1093],
         [-0.5653, -0.0819],
         [-0.8256, -0.0690]],

        [[ 0.2823, -0.1242],
         [-0.3858, -0.2438],
         [-0.8964,  0.2701],
         ...,
         [-0.6260, -0.3201],
         [-0.8223, -0.2419],
         [-0.2527, -0.3082]],

        [[-1.0552, -0.6815],
       

## Special initialization of weights

In [5]:
training_ds, batch1, batch2, output1, output2 = main()

Reading confing file and set up folders...
Load data files...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Loading data to RAM...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Time: 33.71s


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))
/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Loading data to RAM...


/home/bolon/miniconda3/envs/weather/lib/python3.7/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


Time: 6.19s
Define model...
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
Train model...
Epoch : 0

In [6]:
batch1

tensor([[[ 0.1883,  0.1393,  1.3354,  ...,  0.0612,  1.5666,  1.8796],
         [ 0.1283, -0.5404,  1.4066,  ...,  0.1223,  0.5305,  0.5726],
         [-0.0319, -0.3298,  1.2612,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [-1.2608, -0.0810, -0.8427,  ..., -0.1220,  0.9766,  0.8882],
         [-1.3157, -0.1601, -0.8428,  ..., -0.1220,  1.7180,  1.9259],
         [-1.4062, -0.0637, -0.8352,  ..., -0.0609,  1.5136,  1.8794]],

        [[ 0.3941,  2.1510, -0.8225,  ...,  0.0612,  1.5666,  1.8796],
         [ 0.4551,  1.3161, -0.8169,  ...,  0.1223,  0.5305,  0.5726],
         [ 0.5762,  1.4148, -0.8169,  ...,  0.1223,  1.7418,  1.4749],
         ...,
         [-0.0345,  0.7209,  1.4839,  ..., -0.1220,  0.9766,  0.8882],
         [-0.4020,  0.0276,  1.5822,  ..., -0.1220,  1.7180,  1.9259],
         [-0.0691,  0.6317,  1.5415,  ..., -0.0609,  1.5136,  1.8794]],

        [[ 0.0521,  0.4949, -0.8214,  ...,  0.0612,  1.5666,  1.8796],
         [ 0.2914,  0.6639, -0.8265,  ...,  0

In [7]:
output1

tensor([[[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        ...,

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]],

        [[nan, nan],
         [nan, nan],
         [nan, nan],
         ...,
         [nan, nan],
         [nan, nan],
         [nan, nan]]], device='cuda:0', grad_fn=<AsStridedBackward>)